# config.mk
#
# Product-specific compile-time definitions.
#

#Generate DTBO image
BOARD_KERNEL_SEPARATED_DTBO := true

### Dynamic partition Handling
ifneq ($(strip $(BOARD_DYNAMIC_PARTITION_ENABLE)),true)
  ifeq ($(ENABLE_VENDOR_IMAGE), true)
      BOARD_VENDORIMAGE_PARTITION_SIZE := 1073741824
  endif
  BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3221225472
  BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
  ifeq ($(ENABLE_AB), true)
      TARGET_NO_RECOVERY := true
      BOARD_USES_RECOVERY_AS_BOOT := true
  else
      BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x04000000
  endif
else
  # System_ext support
  TARGET_COPY_OUT_SYSTEM_EXT := system_ext
  BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4

  # Define the Dynamic Partition sizes and groups.
  ifeq ($(ENABLE_AB), true)
    BOARD_SUPER_PARTITION_SIZE := 12884901888
  else
    BOARD_SUPER_PARTITION_SIZE := 5318967296
  endif
  BOARD_SUPER_PARTITION_GROUPS := qti_dynamic_partitions
  BOARD_QTI_DYNAMIC_PARTITIONS_SIZE := 5314772992
  BOARD_QTI_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor system_ext
  BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
  BOARD_EXT4_SHARE_DUP_BLOCKS := true
endif

ifeq ($(BOARD_KERNEL_SEPARATED_DTBO),true)
    # Enable DTBO for recovery image
    BOARD_INCLUDE_RECOVERY_DTBO := true
endif
### Dynamic partition Handling

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a9

TARGET_SEPOLICY_DIR := gen3_metal

BOARD_SECCOMP_POLICY := device/qcom/$(TARGET_BOARD_PLATFORM)/seccomp

TARGET_NO_BOOTLOADER := false
TARGET_USES_UEFI := true
TARGET_NO_KERNEL := false

TARGET_USES_IOPHAL := true

BUILD_BROKEN_DUP_RULES := true

-include $(QCPATH)/common/msmnile_au/BoardConfigVendor.mk

# Some framework code requires this to enable BT
BOARD_HAVE_BLUETOOTH := true
BOARD_USES_WIPOWER := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/qcom/common/automotive

USE_OPENGL_RENDERER := true
BOARD_USE_LEGACY_UI := true

# Set Header version for bootimage
#Disable appended dtb
TARGET_KERNEL_APPEND_DTB := false

#Enable dtb in boot image and boot image header version 3 support.
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
ifeq ($(ENABLE_AB), true)
BOARD_USES_RECOVERY_AS_BOOT := true
TARGET_NO_RECOVERY := true
endif

BOARD_BOOT_HEADER_VERSION := 3
BOARD_MKBOOTIMG_ARGS := --header_version $(BOARD_BOOT_HEADER_VERSION)

# Defines for enabling A/B builds
AB_OTA_UPDATER := true
# Full A/B partition update set
# AB_OTA_PARTITIONS := xbl rpm tz hyp pmic modem abl boot keymaster cmnlib cmnlib64 system bluetooth

# Minimum partition set for automation to test recovery generation code
# Packages generated by using just the below flag cannot be used for updating a device. You must pass
# in the full set mentioned above as part of your make commandline
AB_OTA_PARTITIONS ?= system vendor system_ext
#TARGET_NO_RECOVERY := true
#BOARD_USES_RECOVERY_AS_BOOT := true
BOARD_USES_METADATA_PARTITION := true

#Enable compilation of oem-extensions to recovery
#These need to be explicitly 
ifneq ($(AB_OTA_UPDATER),true)
    TARGET_RECOVERY_UPDATER_LIBS += librecovery_updater_msm
endif

ifneq ($(strip $(BOARD_DYNAMIC_PARTITION_ENABLE)),true)
  TARGET_RECOVERY_FSTAB := device/qcom/msmnile_au/fstab.qcom
else
  TARGET_RECOVERY_FSTAB := device/qcom/msmnile_au/fstab.qcom
endif


#Enable split vendor image
ENABLE_VENDOR_IMAGE := true
ifeq ($(ENABLE_VENDOR_IMAGE), true)
#BOARD_VENDORIMAGE_PARTITION_SIZE := 1073741824
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor
BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED := true
endif
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x06000000
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 0x06000000
#BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3221225472
BOARD_USERDATAIMAGE_PARTITION_SIZE := 10737418240
BOARD_PERSISTIMAGE_PARTITION_SIZE := 33554432
BOARD_METADATAIMAGE_PARTITION_SIZE := 16777216
BOARD_PREBUILT_DTBOIMAGE := out/target/product/msmnile_au/prebuilt_dtbo.img
BOARD_DTBOIMG_PARTITION_SIZE := 0x0800000
BOARD_PERSISTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)

BOARD_VENDOR_KERNEL_MODULES := \
     $(KERNEL_MODULES_OUT)/hsi2s.ko
#    $(KERNEL_MODULES_OUT)/audio_apr.ko \
#    $(KERNEL_MODULES_OUT)/audio_snd_event.ko \
#    $(KERNEL_MODULES_OUT)/audio_q6_notifier.ko \
#    $(KERNEL_MODULES_OUT)/audio_adsp_loader.ko \
#    $(KERNEL_MODULES_OUT)/audio_q6.ko \
#    $(KERNEL_MODULES_OUT)/audio_platform.ko \
#    $(KERNEL_MODULES_OUT)/audio_hdmi.ko \
#    $(KERNEL_MODULES_OUT)/audio_stub.ko \
#    $(KERNEL_MODULES_OUT)/audio_native.ko \
#    $(KERNEL_MODULES_OUT)/audio_machine_msmnile.ko \
#    $(KERNEL_MODULES_OUT)/wil6210.ko \
#    $(KERNEL_MODULES_OUT)/msm_11ad_proxy.ko \
#    $(KERNEL_MODULES_OUT)/emac_dwc_eqos.ko \

#----------------------------------------------------------------------
# Compile Linux Kernel
#----------------------------------------------------------------------
ifeq ($(KERNEL_DEFCONFIG),)
    ifeq ($(TARGET_BUILD_VARIANT),user)
        KERNEL_DEFCONFIG := gen3auto-qgki_defconfig
    else
        KERNEL_DEFCONFIG := gen3auto-qgki-debug_defconfig
    endif
endif

# install lkdtm only for userdebug and eng build variants
ifneq (,$(filter userdebug eng, $(TARGET_BUILD_VARIANT)))
    ifneq (,$(findstring debug_defconfig, $(KERNEL_DEFCONFIG)))
        BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/lkdtm.ko
    endif
endif

ifeq (,$(findstring -qgki-debug_defconfig,$(KERNEL_DEFCONFIG)))
$(warning #### GKI config ####)
VENDOR_RAMDISK_KERNEL_MODULES := proxy-consumer.ko \
				 rpmh-regulator.ko \
				 refgen.ko \
				 stub-regulator.ko \
				 clk-dummy.ko \
				 clk-qcom.ko \
				 clk-rpmh.ko \
				 gcc-sm8150.ko \
				 qnoc-sm8150.ko \
				 cmd-db.ko \
				 qcom_rpmh.ko \
				 rpmhpd.ko \
				 icc-bcm-voter.ko \
				 icc-rpmh.ko \
				 pinctrl-msm.ko \
				 pinctrl-sm8150.ko \
				 _qcom_scm.ko \
				 secure_buffer.ko \
				 iommu-logger.ko \
				 qcom-arm-smmu-mod.ko \
				 phy-qcom-ufs.ko \
				 phy-qcom-ufs-qmp-v4.ko \
				 phy-qcom-ufs-qrbtc-sdm845.ko \
				 ufs-qcom.ko \
				 qbt_handler.ko \
				 qcom_watchdog.ko \
				 qcom-pdc.ko \
				 qpnp-power-on.ko \
				 msm-poweroff.ko \
				 sdhci-msm.ko \
				 cqhci.ko \
				 cqhci-crypto.ko \
				 cqhci-crypto-qti.ko \
				 memory_dump_v2.ko \
				 qnoc-qos.ko \
				 msm_ion_heaps.ko \
				 msm-geni-se.ko \
				 msm_geni_serial.ko \
				 msm_drm.ko \
				 msm_cfg.ko \
				 subsys-pil-tz.ko \
				 peripheral-loader.ko \
				 smem.ko \
				 qmi_helpers.ko \
				 subsystem_restart.ko \
				 msm_kgsl.ko \
				 governor_gpubw_mon.ko \
				 governor_msm_adreno_tz.ko \
				 pinctrl-sx150x.ko \
				 dwc3.ko \
				 dwc3-msm.ko \
				 phy-qcom-emu.ko \
				 phy-msm-ssusb-qmp.ko \
				 phy-msm-snps-hs.ko \
				 phy-generic.ko \
				 ns.ko \
				 qrtr.ko \
				 qrtr-smd.ko \
				 usb_f_cdev.ko \
				 dispcc-sm8150.ko \
				 scc-sm8150.ko \
				 pinctrl-slpi.ko \
				 i2c-msm-geni.ko \
				 i2c-mux.ko \
				 analogix-anx7625.ko \
				 msm_qmp.ko \
				 i2c-mux-pca954x.ko \
				 gpucc-sm8150.ko \
				 qpnp-power-on.ko \
				 spmi-pmic-arb.ko \
				 qcom-spmi-pmic.ko \
				 spmi-pmic-arb-debug.ko \
				 qcom-spmi-temp-alarm.ko \
				 pinctrl-spmi-gpio.ko \
				 pinctrl-spmi-mpp.ko \
				 rtc-pm8xxx.ko \
				 clk-spmi-pmic-div.ko \
				 qcom-spmi-adc5.ko \
				 qcom-spmi-sdam.o \
				 regmap-spmi.ko \
				 qcom-vadc-common.ko \
				 qseecom-mod.ko \
				 hdcp_qseecom.ko \
				 msm_rng.ko \
				 smcinvoke.ko \
				 ufshcd-crypto-qti.ko \
				 crypto-qti-common.ko \
				 crypto-qti-tz.ko \
				 cdsp-loader.ko \
				 msm_dma_iommu_mapping.ko \
				 i2c-dev.ko \
				 spidev.ko \
				 frpc-adsprpc.ko \
				 service-notifier.ko \
				 service-locator.ko \
				 rpmsg_core.ko \
				 qcom_glink_smem.ko \
				 qcom_glink_spss.ko \
				 glink_probe.ko \
				 glink_pkt.ko \
				 qsee_ipc_irq.ko \
				 qsee_ipc_irq_bridge.ko \
				 spcom.ko \
				 clk-aop-qmp.ko \
				 cdsprm.ko \
				 qcom-cpufreq-hw.ko \
				 smp2p.ko \
				 osm-l3.ko \
				 mhi_bus.ko \
				 mhi_uci.ko \
				 qcom_hwspinlock.ko \
				 msm_sharedmem.ko \
				 qcom_glink_native.ko \
				 spss_utils.ko \
				 qcom-apcs-ipc-mailbox.ko \
				 smem_state.ko \
				 socinfo.ko
else
$(warning #### QGKI config ####)
endif

BOARD_DO_NOT_STRIP_VENDOR_MODULES := true

BOARD_VENDOR_KERNEL_MODULES += $(shell ls $(KERNEL_MODULES_OUT)/*.ko)
TARGET_USES_ION := true
TARGET_USES_NEW_ION_API :=true
TARGET_USES_QCOM_BSP := false
BOARD_KERNEL_CMDLINE := console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0xa90000 androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=4096 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 androidboot.usbcontroller=a600000.dwc3 androidboot.recover_usb=1 androidboot.selinux=enforcing hibernate=nocompress noswap_randomize pcie_ports=compat

BOARD_EGL_CFG := device/qcom/$(TARGET_BOARD_PLATFORM)/egl.cfg

BOARD_KERNEL_BASE        := 0x00000000
BOARD_KERNEL_PAGESIZE    := 4096
BOARD_KERNEL_TAGS_OFFSET := 0x01E00000
BOARD_RAMDISK_OFFSET     := 0x02000000

TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CROSS_COMPILE_PREFIX := $(shell pwd)/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-androidkernel-

KERN_PATH := kernel/msm-5.4/
$(shell if ! [ -L $(KERN_PATH)gen_headers_arm64.bp ]; then rm $(KERN_PATH)gen_headers_arm64.bp && ln -s gen_headers_arm64_auto.bp $(KERN_PATH)gen_headers_arm64.bp; fi)
$(shell if ! [ -L $(KERN_PATH)gen_headers_arm.bp ]; then rm $(KERN_PATH)gen_headers_arm.bp && ln -s gen_headers_arm_auto.bp $(KERN_PATH)gen_headers_arm.bp; fi)

MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024

BOARD_USES_GENERIC_AUDIO := true
BOARD_QTI_CAMERA_32BIT_ONLY := true
TARGET_NO_RPC := true

TARGET_PLATFORM_DEVICE_BASE := /devices/soc.0/
TARGET_INIT_VENDOR_LIB := libinit_msm


TARGET_COMPILE_WITH_MSM_KERNEL := true

#Enable PD locater/notifier
TARGET_PD_SERVICE_ENABLED := true

#Enable peripheral manager
TARGET_PER_MGR_ENABLED := true

# Enable dex pre-opt to speed up initial boot
ifeq ($(HOST_OS),linux)
    ifeq ($(WITH_DEXPREOPT),)
      WITH_DEXPREOPT := true
      WITH_DEXPREOPT_PIC := true
      ifneq ($(TARGET_BUILD_VARIANT),user)
        # Retain classes.dex in APK's for non-user builds
        DEX_PREOPT_DEFAULT := nostripping
      endif
    endif
endif

TARGET_USES_GRALLOC1 := true

# Enable sensor multi HAL
USE_SENSOR_MULTI_HAL := false

# Enable sensor Version V_1
USE_SENSOR_HAL_VER := 1.0

#Add non-hlos files to ota packages
ADD_RADIO_FILES := true

#Enable INTERACTION_BOOST
TARGET_USES_INTERACTION_BOOST := true

#Enable DRM plugins 64 bit compilation
TARGET_ENABLE_MEDIADRM_64 := true

#namespace definition for librecovery_updater
#differentiate legacy 'sg' or 'bsg' framework
SOONG_CONFIG_NAMESPACES += ufsbsg
SOONG_CONFIG_ufsbsg += ufsframework
SOONG_CONFIG_ufsbsg_ufsframework := bsg


#----------------------------------------------------------------------
# wlan specific
#----------------------------------------------------------------------
ifeq ($(strip $(BOARD_HAS_QCOM_WLAN)),true)
include device/qcom/wlan/msmnile_au/BoardConfigWlan.mk
endif

#Flag to enable System SDK Requirements.
#All vendor APK will be compiled against system_current API set.
BOARD_SYSTEMSDK_VERSIONS:= 31

#Enable VNDK Compliance
BOARD_VNDK_VERSION:=current

BUILD_BROKEN_NINJA_USES_ENV_VARS := SDCLANG_AE_CONFIG SDCLANG_CONFIG SDCLANG_SA_ENABLED SDCLANG_CONFIG_AOSP
BUILD_BROKEN_PREBUILT_ELF_FILES := true
BUILD_BROKEN_USES_BUILD_HOST_SHARED_LIBRARY := true
BUILD_BROKEN_USES_BUILD_HOST_EXECUTABLE := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true
BUILD_BROKEN_USES_BUILD_HOST_STATIC_LIBRARY := true

#Flag for Early Ethernet
IS_EARLY_ETH_ENABLED := 1

#################################################################################
# This is the End of BoardConfig.mk file.
# Now, Pickup other split Board.mk files:
#################################################################################
# TODO: Relocate the system Board.mk files pickup into qssi lunch, once it is up.
-include vendor/qcom/defs/board-defs/system/*.mk
-include vendor/qcom/defs/board-defs/vendor/*.mk
#################################################################################
include device/qcom/sepolicy_vndr/SEPolicy.mk
#Enable Camera2 APIs on automotive builds
ENABLE_CAMERA_SERVICE := true
